### ISSUE TITLE
fix related posts hyperlink style

### ISSUE THREAD

**Issue by radames** [youthradio/mh-supportingfriends#6]
When ACF doesn't return a color, add a default color for border-bottom
please submit the fix to our original template as well 
https://github.com/youthradio/static-nuxt-template

thanks

**Comment by shagia** [comment]
[d246601](https://github.com/youthradio/note-to-parents/commit/d246601f7389c099a93d230fc2542be5557abceb) checks if the secondary color exists, if it does, applies it, and if not, just defaults to our green
